sudo: false

addons:
  apt:
    packages:
      - curl
      - make
      - zlib1g-dev

before_install:
  - export PATH=$PATH:$PWD/rock/bin:$PWD/sam:$PWD
  - export OOC_LIBS=$PWD
  - git clone --depth=1 git://github.com/fasterthanlime/rock.git
  - (cd rock && make rescue)
  - git clone --depth=1 git://github.com/fasterthanlime/sam.git
  - (cd sam && rock --quiet sam.use)
  - git clone --depth=1 git://github.com/fasterthanlime/nagaqueen.git

script:
  - make clean all
  - cork cork.use

notifications:
  webhooks: http://rcmp.pw/freenode/ooc-lang

